git:
  skipHookPrefix: WIP
  autoFetch: false
  autoRefresh: true
  autoForwardBranches: none
  fetchAll: true
  autoStageResolvedConflicts: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName} --}
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: true
  truncateCopiedCommitHashesTo: 12
  pagers: 
    - pager: delta --dark --paging=never --line-numbers
      colorArg: always 
    - externalDiffCommand: difft --color=always

gui:
  nerdFontsVersion: "3"
